                    //   ***JS-A1#2*** 
                    //   ***TASK 1D***

//What is a variable. What should be kept in mind while naming a variable

//VARIABLE - Variables are named values and can store any type of JavaScript value.

//Variable names are pretty flexible as long as we follow a few rules:
//Start them with a letter, underscore _, or dollar sign $.
//After the first letter, we can use numbers, as well as letters, underscores, or dollar signs.
//Not use a reserved keyword
//case sensitive